# Generated by Django 4.2.11 on 2026-03-10 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('current_country', models.CharField(blank=True, max_length=80)),
                ('university_name', models.CharField(blank=True, max_length=150)),
                ('degree_level', models.CharField(blank=True, choices=[('bachelor', "Bachelor's"), ('master', "Master's"), ('phd', 'PhD'), ('other', 'Other')], max_length=20)),
                ('major', models.CharField(blank=True, max_length=100)),
                ('year_of_study', models.CharField(blank=True, choices=[('1', '1st year'), ('2', '2nd year'), ('3', '3rd year'), ('4', '4th year'), ('5', '5th year'), ('other', 'Other')], max_length=10)),
                ('languages', models.CharField(blank=True, help_text='e.g. English, Russian, Korean', max_length=200)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, help_text='Your current country', max_length=80)),
                ('target_country', models.CharField(blank=True, help_text='Country you want to study in', max_length=80)),
                ('target_degree', models.CharField(blank=True, choices=[('bachelor', "Bachelor's"), ('master', "Master's"), ('phd', 'PhD'), ('other', 'Other')], max_length=20)),
                ('intended_major', models.CharField(blank=True, max_length=100)),
                ('preferred_language', models.CharField(blank=True, help_text='e.g. English, German', max_length=80)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
