services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: studybridge_db
      POSTGRES_USER: studybridge_user
      POSTGRES_PASSWORD: "7001070036"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U studybridge_user -d studybridge_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
